server:
  port : 8082
spring:
  datasource:
    url: jdbc:postgresql://psql:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
    show-sql: true
logging:
  level:
    root: warn
