services:
  nginx:
    build: ./nginx/prod_local/
    image: pvt2024/nginx_local:latest
    restart: always
    ports:
      - 80:80
    links:
      - gateway

  psql:
    image: pvt2024/database:$TAG
      
  frontend:
    image: pvt2024/frontend:$TAG
      
  gateway:
    image: pvt2024/gateway:$TAG
    
  api:
    image: pvt2024/api:$TAG
    
