version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/development.conf:/etc/nginx/nginx.conf
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    links:
      - gateway
  psql:
    build: ./database
    environment:
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=yotei123
      - POSTGRES_DB=yotei
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
  frontend:
    image: pvt2023/frontend:latest
    ports:
      - "3000:3000"
    links:
      - psql
  gateway:
    image: pvt2023/gateway:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=yotei123
      - POSTGRES_DB=yotei
    links:
      - user-api
  user-api:
    image: pvt2023/api:latest
    ports:
      - "8085:8085"
    links:
      - psql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=yotei123
      - POSTGRES_DB=yotei

volumes:
  pgdata:

#                 O  O  O
#                        O
#                  ._, __|__.
#                  || ||_____\
#                  || ||    |
#            .---------------------------.
#             \   O   O   O   O -YOTEI- /
#        ~ ~ ~ ~ ~ ~ ~ ~  ~ ~ ~ ~ ~ ~ ~ ~
#      ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
