version: "3.7"
services:

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/development.conf:/etc/nginx/nginx.conf
      - ./api-docs:/var/www/html/api-docs
      - ./javadocs:/var/www/html/javadocs
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    links:
      - gateway

  # Database need to be created first, check if depends_on is needed
  psql:
    image: pvt2024/database:feature

      
  frontend:
    image: pvt2024/frontend:feature
      
  gateway:
    image: pvt2024/gateway:feature
    ports:
      - "8080:8080"
      
  api:
    image: pvt2024/api:feature
    restart: always


    #                 O  O  O
    #                        O
    #                  ._, __|__.
    #                  || ||_____\
    #                  || ||    |
    #            .---------------------------.
    #             \   O   O   O   O -YOTEI- /
    #        ~ ~ ~ ~ ~ ~ ~ ~  ~ ~ ~ ~ ~ ~ ~ ~
    #      ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
