services:
  nginx:
    build: ./nginx/
    image: pvt2024/nginx:latest
    restart: always
    volumes:
      - certbotwww:/var/www/certbot/:ro
      - certificate:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    links:
      - gateway

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - certificate:/etc/letsencrypt/:rw
      - certbotwww:/var/www/certbot/:rw
      
  psql:
    image: pvt2024/database:latest
      
  frontend:
    image: pvt2024/frontend:latest
      
  gateway:
    image: pvt2024/gateway:latest
    
  api:
    image: pvt2024/api:latest
    
volumes:
  certificate:
  certbotwww:
