services:
  nginx:
    build: ./nginx/local/
    image: pvt2024/nginx:latest
    restart: always
    ports:
      - 80:80
    links:
      - gateway

  psql:
    image: pvt2024/database:latest
      
  frontend:
    image: pvt2024/frontend:latest
      
  gateway:
    image: pvt2024/gateway:latest
    
  api:
    image: pvt2024/api:latest
    
