services:
  nginx:
    build: ./nginx/
    image: pvt2024/nginx:$TAG
    restart: always
    volumes:
      - certbotwww:/var/www/certbot/:ro
      - certificate:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    links:
      - gateway

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certificate:/etc/letsencrypt/:rw
      - certbotwww:/var/www/certbot/:rw
      
  psql:
    image: pvt2024/database:$TAG
      
  frontend:
    image: pvt2024/frontend:$TAG
      
  gateway:
    image: pvt2024/gateway:$TAG
    
  api:
    image: pvt2024/api:$TAG
    
volumes:
  certificate:
  certbotwww:
