import { test, expect } from '@playwright/test';

test.describe("GradingDuring tests", () => {
    test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/');
    await page.locator('#username-input').click();
    await page.locator('#username-input').fill('admin');
    await page.locator('#username-input').press('Tab');
    await page.locator('#password-input').fill('admin');
    await page.locator('#password-input').press('Enter');
    await page.locator('#hamburger-button').click();
    await page.getByRole('button', { name: 'Gradering' }).click();
    await page.locator('._btnAddActivity_1qfu5_1').click();
    await page.getByRole('button', { name: 'KYU GULT BÄLTE' }).click();
    await page.getByPlaceholder('Lägg till ny deltagare').click();
    await page.getByPlaceholder('Lägg till ny deltagare').fill('Noa');
    await page.locator('#plus-icon').click();
    await page.getByPlaceholder('Lägg till ny deltagare').click();
    await page.getByPlaceholder('Lägg till ny deltagare').fill('Lars');
    await page.locator('#plus-icon path').click();
    await page.getByRole('button', { name: 'Forsätt' }).click();
    await expect(page.locator('#root')).toContainText('1. Shotei uchi, jodan, rak stöt med främre och bakre handen');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('2. Shotei uchi, chudan, rak stöt med främre och bakre handen');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('3. Gedan geri, rak spark med främre och bakre benet');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('1. O soto osae, utan grepp, nedläggning snett bakåt');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('1. Koshi otoshi, utan grepp, nedläggning snett bakåt');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('1. Grepp i två handleder framifrån Frigöring');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('2. Grepp i två handleder bakifrån Frigöring');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('3. Grepp i håret bakifrån Tettsui uchi, frigöring');
    await page.locator('#next_technique path').click();
    await expect(page.locator('#root')).toContainText('4. Försök till stryptag framifrån Jodan soto uke');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('5. Stryptag framifrån Kawashi, frigöring');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('6. Stryptag bakifrån Maesabaki, kawashi, frigöring');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('7. Stryptag med armen Maesabaki, kuzure ude osae, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('8. Försök till kravattgrepp från sidan Jodan chikai uke, kawashi, koshi otoshi, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('9. Grepp i ärmen med drag O soto osae, ude henkan gatame');
    await page.locator('#next_technique path').click();
    await expect(page.locator('#root')).toContainText('10. Livtag under armarna framifrån Tate hishigi, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('11. Stryptag mot liggande sittande vid sidan Frigöring, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('12. Hotfullt närmande mot liggande Uppgång bakåt');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('13. Hotfullt närmande Hejda med tryck');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('14. Kort svingslag Jodan chikai uke, kawashi, koshi otoshi, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('15. Långt svingslag Morote jodan uke, o soto osae, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('16. Påkslag mot huvudet Ju morote jodan uke');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('17. Påkslag mot huvudet, backhand Ju morote jodan uke');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('18. Knivhot mot magen Grepp, shotei uchi jodan');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('1. Försök till stryptag framifrån - Försök till kravattgrepp från sidan Jodan soto uke - Jodan chikai uke, kawashi, koshi otoshi, ude henkan gatame');
    await page.locator('#next_technique').getByRole('img').click();
    await expect(page.locator('#root')).toContainText('1. Försvar mot en motståndare');
    });
})