spring:
  cloud:
    gateway:
      routes:
        # id: choose an appropriate id for your service
        # uri: the uri of the service to route to
        # predicates: Use Path predicate to define the api-mapping that goes to the micro-service

        - id: all
          uri: ${BACKEND_HOST}
          predicates:
            - Path=/api/**

        - id: user
          uri: ${BACKEND_HOST}
          predicates:
            - Path=/user/**
        # Please remember to add the same service to application-docker.yml!
        # (also remember to change localhost to the name of the container
        #  name specified in docker-compose.yml (in the project's top directory))
        ################################################################################################
        # Do not put any other routes below here!
        - id: webserver
          uri: ${WEBSERVER_HOST}
          predicates:
            - Path=/**

logging:
  level:
    root: debug
