INSERT INTO technique_weave (name, description) VALUES ('Demo Väv', 'Kampsport är en bred och mångfacetterad värld som omfattar olika discipliner och tekniker, utvecklade för både självförsvar och tävling. Från traditionella stilar som karate och taekwondo, till moderna system som brasiliansk jiu-jitsu och mixed martial arts (MMA), erbjuder kampsport något för alla.');
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Gör grepp i handleden', '', -1, true, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Gör fritagande', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Plockar upp en påk', '', -1, true, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Ju morote jodan uke', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae neutral', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae gard', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Gör hotfullt närmande', '', -1, true, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Hejdar med tryck', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Faller baklänges', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae gard', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae neutral', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Gräppar nacken och knästöt', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'gedan juji uke', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Grepp i håret', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'gedan geri', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'gör fritagning', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Försök till stryptag', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Jodan soto uke', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae neutral', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae gard', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Uki otoshi', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae neutral', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae gard', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'Liggande stryptag', '', -1, false, 2);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'ude henkan gatame', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae gard', '', -1, false, 1);
INSERT INTO node (parent_weave, name, description, technique, attack, participant) VALUES (1, 'kamae neutral', '', -1, false, 2);
INSERT INTO edges (from_node_id, to_node_id) VALUES (1, 2);
INSERT INTO edges (from_node_id, to_node_id) VALUES (3, 4);
INSERT INTO edges (from_node_id, to_node_id) VALUES (2, 3);
INSERT INTO edges (from_node_id, to_node_id) VALUES (4, 6);
INSERT INTO edges (from_node_id, to_node_id) VALUES (2, 7);
INSERT INTO edges (from_node_id, to_node_id) VALUES (4, 5);
INSERT INTO edges (from_node_id, to_node_id) VALUES (9, 10);
INSERT INTO edges (from_node_id, to_node_id) VALUES (7, 8);
INSERT INTO edges (from_node_id, to_node_id) VALUES (9, 11);
INSERT INTO edges (from_node_id, to_node_id) VALUES (8, 9);
INSERT INTO edges (from_node_id, to_node_id) VALUES (8, 12);
INSERT INTO edges (from_node_id, to_node_id) VALUES (12, 13);
INSERT INTO edges (from_node_id, to_node_id) VALUES (16, 17);
INSERT INTO edges (from_node_id, to_node_id) VALUES (15, 17);
INSERT INTO edges (from_node_id, to_node_id) VALUES (8, 17);
INSERT INTO edges (from_node_id, to_node_id) VALUES (13, 14);
INSERT INTO edges (from_node_id, to_node_id) VALUES (14, 15);
INSERT INTO edges (from_node_id, to_node_id) VALUES (14, 16);
INSERT INTO edges (from_node_id, to_node_id) VALUES (18, 19);
INSERT INTO edges (from_node_id, to_node_id) VALUES (17, 18);
INSERT INTO edges (from_node_id, to_node_id) VALUES (2, 17);
INSERT INTO edges (from_node_id, to_node_id) VALUES (18, 20);
INSERT INTO edges (from_node_id, to_node_id) VALUES (17, 21);
INSERT INTO edges (from_node_id, to_node_id) VALUES (21, 22);
INSERT INTO edges (from_node_id, to_node_id) VALUES (21, 23);
INSERT INTO edges (from_node_id, to_node_id) VALUES (21, 24);
INSERT INTO edges (from_node_id, to_node_id) VALUES (24, 25);
INSERT INTO edges (from_node_id, to_node_id) VALUES (25, 26);
INSERT INTO edges (from_node_id, to_node_id) VALUES (25, 27);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 1, -109, 47);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 3, 53, -87);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 2, 55, 47);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 4, 239, -90);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 5, 381, -182);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 6, 386, -88);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 7, -169, 186);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 8, -58, 298);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 10, 122, 150);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 9, 2, 189);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 11, 130, 227);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 12, -184, 495);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 13, -24, 489);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 14, 63, 398);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 16, 197, 404);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 15, 198, 324);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 19, 444, -11);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 18, 321, 41);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 17, 361, 234);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 21, 509, 204);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 20, 453, 89);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 22, 639, 141);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 25, 434, 398);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 24, 509, 314);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 23, 635, 260);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 26, 572, 396);
INSERT INTO weave_representation (parent_weave_id, node_id, node_x_pos, node_y_pos) VALUES (1, 27, 576, 480);
INSERT INTO technique_chain (name, description, parent_weave_id) VALUES ('Demo Tråd', 'Kampsportens kulturella aspekt är också betydande, med många traditioner och ritualer som hedrar dess historia och ursprung. Bältesgraderingar, dojos och respekt för instruktörer är alla viktiga element som förstärker disciplin och ödmjukhet. Oavsett om man tränar för tävling, självförsvar eller personlig utveckling, erbjuder kampsport en rik och givande väg till förbättrad fysisk och mental hälsa. Det är en livsstil som främjar harmoni mellan kropp och själ.', 1);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (1, 1, 1);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (2, 1, 2);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (7, 1, 3);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (8, 1, 4);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (17, 1, 5);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (21, 1, 6);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (24, 1, 7);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (25, 1, 8);
INSERT INTO in_chain (node_id, chain_id, pos_in_chain) VALUES (26, 1, 9);
