spring:
  cloud:
    gateway:
      routes:
        # id: choose an appropriate id for your service
        # uri: the uri of the service to route to
        # predicates: Use Path predicate to define the api-mapping that goes to the micro-service
        - id: all
          uri: http://user-api:8085
          predicates:
            - Path=/api/**

        - id: user
          uri: http://user-api:8085
          predicates:
            - Path=/user/**

        ################################################################################################
        #do not put any other routes below here
        - id: webserver
          uri: http://frontend:3000
          predicates:
            - Path=/**

logging:
  level:
    root: warn
