server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://psql:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
jwt:
    secret: "pvt"
logging:
  level:
    root: warn
