server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
