/**
 * The Tag API microservice.
 * @Author Team 5 Verona
 */
package se.umu.cs.pvt.tagapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Runs the service
 */
@SpringBootApplication
public class TagApiApplication {

    /**
     * Main autogenerated by Spring. Don't touch!
     * @param args args
     */
    public static void main(String[] args) {
        SpringApplication.run(TagApiApplication.class, args);
    }
}
