stages:
  - deploy

deploy-api-docs:
  stage: deploy
  image: python:3.8-alpine3.17
  before_script:
    - apk add rsync openssh-client
    - python -m pip install --upgrade pip
    - pip install mkdocs mkdocs-material
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - cd api-docs && mkdocs build -d deploy
    - rsync -avzhuP ./deploy/* pvt@imp.cs.umu.se:/home/pvt/pvt-web/api-docs/
  only:
    - main
