--
-- INSERTS FOR ACTIVITIES
--
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (1, 285, null, 'Uppvärmning', 1, 'Uppvärmning Springa', 'Springa i 10 minuter', 10, 1);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (1, 286, null, 'Uppvärmning', 1, 'Uppvärmning Burpees', 'Burpees i 5 minuter', 5, 2);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (1, null, 7, 'Träning', 2, 'Empi uchi träning', 'Empi uchi i 15 minuter', 15, 1);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (1, null, 8, 'Träning', 2, 'Waki gatame träning', 'Waki gatame i 5 minuter', 5, 2);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (1, null, 8, 'Träning', 2, 'Waki gatame träning', 'Waki gatame i 7 minuter', 7, 3);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (1, null, 8, 'Avslut', 3, 'Waki gatame träning', 'Avsluta med Waki gatame i 15 minuter', 15, 4);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (2, 286, null, 'Uppvärmning', 1, 'Uppvärmning Burpees', 'Burpees i 5 minuter', 5, 1);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (2, 287, null, 'Uppvärmning', 1, 'Uppvärmning Jumping Jacks', 'Jumping Jacks i 15 minuter', 15, 2);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (2, null, 8, 'Träning', 2, 'Empi uchi träning', 'Empi uchi i 15 minuter', 15, 1);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (2, null, 6, 'Träning', 2, 'Waki gatame träning', 'Waki gatame i 5 minuter', 5, 2);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (2, null, 6, 'Träning', 2, 'Waki gatame träning', 'Waki gatame i 7 minuter', 7, 3);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (2, null, 6, 'Avslut', 3, 'Waki gatame träning', 'Avsluta med Waki gatame i 15 minuter', 15, 4);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (3, null, null, 'Träning', 1, 'Empi uchi träning', 'Empi uchi i 15 minuter', 15, 1);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (3, null, 2, 'Träning', 1, 'Waki gatame träning', 'Waki gatame i 5 minuter', 5, 2);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (3, null, 2, 'Träning', 1, 'Waki gatame träning', 'Waki gatame i 7 minuter', 7, 3);
INSERT INTO activity (workout_id, exercise_id, technique_id, category_name, category_order, activity_name, activity_desc, activity_duration, activity_order) VALUES (3, null, 2, 'Avslut', 2, 'Waki gatame träning', 'Avsluta med Waki gatame i 15 minuter', 15, 4);