INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Gult', 'FFDD33', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Gult', 'FFDD33', True);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Orange', 'FFA133', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Orange', 'FFA133', True);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Grönt', '0C7D2B', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Grönt', '0C7D2B', True);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Blått', '1E9CE3', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Blått', '1E9CE3', True);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Brunt', '83530C', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Brunt', '83530C', True);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('Svart', '201E1F', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('1 Dan', '201E1F', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('2 Dan', '201E1F', False);
INSERT INTO belt (belt_name, belt_color, is_child) VALUES ('3 Dan', '201E1F', False);