--
-- INSERTS FOR EXERCISE
--
INSERT INTO exercise (name, description, duration) VALUES ('Springa', 'Placera ena foten framför den andra och upprepa!', 10);
INSERT INTO exercise (name, description, duration) VALUES ('Burpees', 'Börja ståendes, gör en armhävning, hoppa upp och klappa händerna över huvudet!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Jumping Jacks', 'Hoppa upp och brett isär benen samtidigt som du tar armarna upp ovanför huvudet, hoppa sedan tillbaka till startpositionen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Squats', 'Stå med fötterna axelbrett isär och gå ner i en knäböj tills låren är parallella med golvet, res dig upp igen!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Armhävningar', 'Börja i en plankposition och sänk kroppen genom att böja armarna, pressa sedan upp igen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan', 'Stöd kroppen på underarmarna och tårna, håll kroppen i en rak linje!', 60);
INSERT INTO exercise (name, description, duration) VALUES ('Fjällklättrare', 'Anta en push-up position och alternera genom att dra knäna mot bröstet!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Utfall', 'Ta ett steg framåt med ett ben och sänk kroppen tills ditt främre knä är böjt i en 90-graders vinkel!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Sit-ups', 'Ligga på rygg med böjda knän och lyft överkroppen mot dina knän!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Rygghävningar', 'Ligga på mage och lyft överkroppen samtidigt som du spänner ryggmusklerna!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Armhävningar på knäna', 'Börja i en plankposition med knäna på marken och sänk kroppen genom att böja armarna, pressa sedan upp igen!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Bulgarian Split Squats', 'Stå med ena foten bakåt på en förhöjning och utför knäböj med den främre benet!', 25);
INSERT INTO exercise (name, description, duration) VALUES ('Tricep Dips', 'Sätt händerna på en bänk bakom dig, sänk kroppen genom att böja armarna och pressa sedan upp igen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Höftlyft', 'Ligga på rygg med böjda knän och lyft höften så att kroppen bildar en rak linje!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan med rotation', 'Anta plankposition och rotera kroppen genom att höja en arm mot taket!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Utfallshopp', 'Ta ett stort steg framåt, böj båda knäna och hoppa sedan upp i luften!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Bicepscurls med hantlar', 'Håll en hantel i varje hand och böj armarna för att lyfta hantlarna mot axlarna!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Sidoplankan', 'Stöd kroppen på ena underarmen och foten, håll kroppen i en rak linje och håll positionen!', 45);
INSERT INTO exercise (name, description, duration) VALUES ('Utfall bakåt', 'Ta ett steg bakåt med ett ben och sänk kroppen tills ditt bakre knä är nära golvet!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Mountain climbers', 'Börja i en push-up position och alternera genom att dra knäna mot bröstet snabbt!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Armhävningar med bred handposition', 'Börja i en plankposition och sänk kroppen genom att böja armarna, pressa sedan upp igen med händerna brett isär!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Rodd med hantlar', 'Böj överkroppen framåt med en hantel i varje hand och dra hantlarna mot magen genom att böja armbågarna!', 25);
INSERT INTO exercise (name, description, duration) VALUES ('Utfall med hopp', 'Ta ett stort steg framåt, böj båda knäna och hoppa sedan upp i luften och byt ben!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Utfallssquats', 'Börja med fötterna axelbrett isär och gör en utfall till höger, återgå till startpositionen och gör sedan en utfall till vänster. Upprepa!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan med knädrag', 'Anta en planka position och dra ett knä i taget mot bröstet under kontroll, återgå till startpositionen och byt ben!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Jump Squats', 'Börja i en knäböjposition, hoppa upp i luften och landa i knäböj igen. Upprepa!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Russian Twist', 'Sitt på golvet med böjda knän och luta dig lite bakåt. Vrid torso åt höger och sedan åt vänster genom att rotera med armar framför bröstet!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Höftabduktion med minibands', 'Placera ett miniband runt benen strax ovanför knäna. Stå med fötterna axelbrett isär och tryck ut knäna åt sidan så långt du kan. Återgå till startpositionen!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Triceps pushdown', 'Fäst ett rep i en träningsmaskin. Stå med fötterna axelbrett isär och armbågarna böjda i en 90-graders vinkel. Pressa ner repen genom att räta ut armarna!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Höftlyft med hantlar', 'Ligga på rygg med böjda knän och håll en hantel på höften. Lyft höften så att kroppen bildar en rak linje och sänk sedan tillbaka till startpositionen!', 25);
INSERT INTO exercise (name, description, duration) VALUES ('V-crunches', 'Ligga på rygg med armarna utsträckta över huvudet och benen rakt framåt. Lyft överkroppen och benen samtidigt och försök att vidröra tårna med händerna!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan med knä till armbåge', 'Anta en plankposition och dra ett knä i taget mot motsatt armbåge under kontroll. Byt sida och upprepa!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Benpress', 'Sätt dig i en benpressmaskin med fötterna på plattformen. Tryck ifrån med fötterna och sträck ut benen utan att låsa knäna. Återgå till startpositionen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Jumping Lunges', 'Börja i en utfallsposition och hoppa upp i luften, byt ben i luften och landa i en utfallsposition med det andra benet framåt!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Push-up med rotation', 'Börja i en push-up position, sänk kroppen genom att böja armarna och när du pressar upp kroppen, rotera torso och sträck upp en arm mot taket!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Lateralhopp', 'Stå med fötterna tillsammans och hoppa åt sidan så långt du kan, landa mjukt och hoppa sedan tillbaka till startpositionen!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Utfall med hantlar', 'Håll en hantel i varje hand och ta ett steg framåt med ett ben, sänk kroppen tills ditt främre knä är böjt i en 90-graders vinkel. Res dig upp igen och upprepa på andra benet!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Bicepscurls med gummiband', 'Stå på ett gummiband med fötterna axelbrett isär och håll ändarna av bandet med händerna. Böj armarna och lyft handtagen mot axlarna!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan med armhävning', 'Anta en plankposition och sänk kroppen genom att böja armarna till en armhävningsposition, pressa sedan upp igen till plankposition. Upprepa!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Sidohopp', 'Stå med fötterna tillsammans, hoppa åt sidan så långt du kan och landa på ett ben. Hoppa sedan åt andra sidan och byt ben!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Hantelrodd', 'Böj överkroppen framåt med en hantel i varje hand och dra hantlarna mot magen genom att böja armbågarna. Sänk sedan hantlarna tillbaka till startpositionen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Utfall med knälyft', 'Ta ett steg framåt med ett ben och utför en knälyftning med det andra benet framför dig. Byt ben och upprepa!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Triceps extensions med hantel', 'Håll en hantel över huvudet med båda händerna och sänk hanteln bakom huvudet genom att böja armbågarna. Sträck ut armarna och återgå till startpositionen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Höftabduktion med viktmanschetter', 'Fäst viktmanschetter runt ankeln och stå med fötterna axelbrett isär. Lyft det ena benet utåt så långt du kan och sänk det sedan tillbaka till startpositionen. Upprepa på det andra benet!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Utfall med rotation', 'Ta ett steg framåt med ett ben och sänk kroppen i en knäböj. När du reser dig upp, rotera överkroppen åt sidan mot det främre benet. Upprepa på det andra benet!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan med benlyft', 'Anta en plankposition och lyft ett ben i taget bakåt utan att svanka eller rotera bäckenet. Återgå till startpositionen och byt ben!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Burpee med knäkick', 'Börja ståendes, gör en armhävning, hoppa upp och utför en knäkick med det ena benet. Upprepa med det andra benet!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Superman', 'Ligga på mage med armarna och benen utsträckta. Lyft överkroppen och benen samtidigt så högt du kan och håll positionen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Hantelcurls', 'Håll en hantel i varje hand med armarna nedåt. Böj armarna och lyft hantlarna mot axlarna. Sänk sedan hantlarna tillbaka till startpositionen!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Sit-ups med twist', 'Ligga på rygg med böjda knän och lyft överkroppen mot dina knän. När du når toppen, rotera överkroppen åt sidan för att vidröra motsatt knä med armbågen. Upprepa på andra sidan!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Mountain climbers med twist', 'Börja i en push-up position och alternera genom att dra knäna mot bröstet och samtidigt rotera överkroppen åt sidan. Upprepa på andra sida!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Benlyft', 'Ligga på rygg med raka ben och lyft benen rakt upp mot taket. Sänk benen långsamt tillbaka till startpositionen utan att släppa ryggen från golvet!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Upphopp', 'Stå med fötterna axelbrett isär och hoppa upp i luften med armarna utsträckta över huvudet. Landa mjukt och upprepa!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Sidoplankan med benlyft', 'Stöd kroppen på ena underarmen och foten i en sidoplankposition. Lyft det övre benet uppåt så högt du kan och sänk det sedan tillbaka till startpositionen. Upprepa på andra sidan!', 30);
INSERT INTO exercise (name, description, duration) VALUES ('Utfallshopp med rotation', 'Ta ett stort steg framåt, böj båda knäna och hoppa sedan upp i luften. När du är i luften, rotera överkroppen åt sidan. Upprepa och byt sida!', 15);
INSERT INTO exercise (name, description, duration) VALUES ('Armhävningar med handklapp', 'Börja i en plankposition och sänk kroppen genom att böja armarna. Pressa upp kroppen explosivt och klappa händerna under dig innan du landar i startpositionen!', 20);
INSERT INTO exercise (name, description, duration) VALUES ('Plankan med benlyft åt sidan', 'Anta en plankposition och lyft ett ben utåt åt sidan så högt du kan. Återgå till startpositionen och byt ben!', 30);


--
-- INSERTS FOR EXERCISE TAG
--
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (285, 40), (285, 45), (285, 50);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (286, 67), (286, 74), (286, 31);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (287, 18), (287, 90), (287, 5);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (288, 30), (288, 32), (288, 64);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (289, 40), (289, 83), (289, 3);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (290, 11), (290, 41), (290, 90);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (291, 54), (291, 14), (291, 9);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (292, 23), (292, 55), (292, 53);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (293, 81), (293, 27), (293, 61);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (294, 89), (294, 64), (294, 84);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (295, 53), (295, 59), (295, 22);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (296, 39), (296, 59), (296, 91);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (297, 46), (297, 29), (297, 47);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (298, 36), (298, 68), (298, 28);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (299, 32), (299, 56), (299, 79);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (300, 6), (300, 75), (300, 34);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (301, 86), (301, 30), (301, 43);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (302, 85), (302, 59), (302, 6);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (303, 77), (303, 34), (303, 6);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (304, 11), (304, 29), (304, 88);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (305, 83), (305, 68), (305, 4);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (306, 32), (306, 72), (306, 77);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (307, 50), (307, 18), (307, 1);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (308, 27), (308, 79), (308, 51);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (309, 83), (309, 57), (309, 2);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (310, 87), (310, 91), (310, 48);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (311, 7), (311, 85), (311, 31);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (312, 84), (312, 72), (312, 46);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (313, 11), (313, 46), (313, 45);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (314, 87), (314, 82), (314, 81);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (315, 33), (315, 84), (315, 10);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (316, 5), (316, 43), (316, 77);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (317, 84), (317, 61), (317, 66);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (318, 35), (318, 47), (318, 61);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (319, 76), (319, 47), (319, 37);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (320, 67), (320, 53), (320, 54);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (321, 8), (321, 84), (321, 10);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (322, 19), (322, 93), (322, 73);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (323, 64), (323, 66), (323, 16);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (324, 40), (324, 16), (324, 2);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (325, 1), (325, 28), (325, 68);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (326, 66), (326, 82), (326, 55);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (327, 37), (327, 28), (327, 86);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (328, 50), (328, 34), (328, 17);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (329, 26), (329, 55), (329, 88);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (330, 59), (330, 64), (330, 20);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (331, 86), (331, 69), (331, 23);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (332, 66), (332, 90), (332, 11);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (333, 84), (333, 10), (333, 29);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (334, 92), (334, 12), (334, 90);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (335, 54), (335, 11), (335, 59);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (336, 49), (336, 52), (336, 93);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (337, 91), (337, 53), (337, 2);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (338, 49), (338, 62), (338, 67);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (339, 23), (339, 5), (339, 21);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (340, 55), (340, 21), (340, 45);
INSERT INTO exercise_tag (ex_id, tag_id) VALUES (341, 12), (341, 5), (341, 63);
