INSERT INTO tag (name) VALUES ('svart');
INSERT INTO tag (name) VALUES ('brunt');
INSERT INTO tag (name) VALUES ('grönt');
INSERT INTO tag (name) VALUES ('blått');
INSERT INTO tag (name) VALUES ('gult');
INSERT INTO tag (name) VALUES ('orange');
INSERT INTO tag (name) VALUES ('vitt');
INSERT INTO tag (name) VALUES ('1 dan');
INSERT INTO tag (name) VALUES ('2 dan');
INSERT INTO tag (name) VALUES ('3 dan');
INSERT INTO tag (name) VALUES ('atemi waza');
INSERT INTO tag (name) VALUES ('kihon waza');
INSERT INTO tag (name) VALUES ('kansetsu waza');
INSERT INTO tag (name) VALUES ('nage waza');
INSERT INTO tag (name) VALUES ('katame waza');
INSERT INTO tag (name) VALUES ('kata');
INSERT INTO tag (name) VALUES ('randori');
INSERT INTO tag (name) VALUES ('jigo waza');
INSERT INTO tag (name) VALUES ('renraku waza');
INSERT INTO tag (name) VALUES ('naga waza');
INSERT INTO tag (name) VALUES ('tachi waza');
INSERT INTO tag (name) VALUES ('taisabaki waza');
INSERT INTO tag (name) VALUES ('ukemi waza');
INSERT INTO tag (name) VALUES ('uke waza');
INSERT INTO tag (name) VALUES ('judo');
INSERT INTO tag (name) VALUES ('throws');
INSERT INTO tag (name) VALUES ('footwork');
INSERT INTO tag (name) VALUES ('uppvärmning');
INSERT INTO tag (name) VALUES ('cardio');
INSERT INTO tag (name) VALUES ('calisthenics');
INSERT INTO tag (name) VALUES ('tekniker');
INSERT INTO tag (name) VALUES ('grundtekniker');
INSERT INTO tag (name) VALUES ('grepp- och strypningar');
INSERT INTO tag (name) VALUES ('kasttekniker');
INSERT INTO tag (name) VALUES ('marktekniker');
INSERT INTO tag (name) VALUES ('form');
INSERT INTO tag (name) VALUES ('fri träning');
INSERT INTO tag (name) VALUES ('kontringstekniker');
INSERT INTO tag (name) VALUES ('kombinationstekniker');
INSERT INTO tag (name) VALUES ('kasttekniker från stående');
INSERT INTO tag (name) VALUES ('ståendetekniker');
INSERT INTO tag (name) VALUES ('rörelsetekniker');
INSERT INTO tag (name) VALUES ('falltekniker');
INSERT INTO tag (name) VALUES ('blockeringstekniker');
INSERT INTO tag (name) VALUES ('kast');
INSERT INTO tag (name) VALUES ('fotarbete');
INSERT INTO tag (name) VALUES ('stående');
INSERT INTO tag (name) VALUES ('konditionsträning');
INSERT INTO tag (name) VALUES ('säkerhetstekniker');
INSERT INTO tag (name) VALUES ('parteringsgrepp');
INSERT INTO tag (name) VALUES ('kombinationsgrepp');
INSERT INTO tag (name) VALUES ('kasttekniker från marken');
INSERT INTO tag (name) VALUES ('falltekniker från olika positioner');
INSERT INTO tag (name) VALUES ('grundtekniker för kamp');
INSERT INTO tag (name) VALUES ('fysisk träning');
INSERT INTO tag (name) VALUES ('samarbetsövningar');
INSERT INTO tag (name) VALUES ('självförsvar');
INSERT INTO tag (name) VALUES ('strypningstekniker');
INSERT INTO tag (name) VALUES ('kombinationstekniker för markkamp');
INSERT INTO tag (name) VALUES ('markkamp');
INSERT INTO tag (name) VALUES ('kombinationstekniker för stående kamp');
INSERT INTO tag (name) VALUES ('stående kamp');
INSERT INTO tag (name) VALUES ('specialtekniker');
INSERT INTO tag (name) VALUES ('taktik och strategi');
INSERT INTO tag (name) VALUES ('träningstips');
INSERT INTO tag (name) VALUES ('teknikanalys');
INSERT INTO tag (name) VALUES ('nybörjare');
INSERT INTO tag (name) VALUES ('avancerad');
INSERT INTO tag (name) VALUES ('träningsrutiner');
INSERT INTO tag (name) VALUES ('självförtroende');
INSERT INTO tag (name) VALUES ('mentalt fokus');
INSERT INTO tag (name) VALUES ('utstrålning och närvaro');
INSERT INTO tag (name) VALUES ('balans och koordination');
INSERT INTO tag (name) VALUES ('grundläggande principer');
INSERT INTO tag (name) VALUES ('taktisk träning');
INSERT INTO tag (name) VALUES ('snabbhet och reaktion');
INSERT INTO tag (name) VALUES ('smidighet och flexibilitet');
INSERT INTO tag (name) VALUES ('träningsupplägg');
INSERT INTO tag (name) VALUES ('kampsportsetikett');
INSERT INTO tag (name) VALUES ('målsättning och motivation');
INSERT INTO tag (name) VALUES ('utrustning och klädsel');
INSERT INTO tag (name) VALUES ('smärthantering och skadeförebyggande');
INSERT INTO tag (name) VALUES ('jämnvikts- och tyngdpunktstekniker');
INSERT INTO tag (name) VALUES ('timing och rytmd');
INSERT INTO tag (name) VALUES ('försvar mot olika attacker');
INSERT INTO tag (name) VALUES ('kampstrategier');
INSERT INTO tag (name) VALUES ('uppmärksamhet och observation');
INSERT INTO tag (name) VALUES ('kommunikation och samarbete');
INSERT INTO tag (name) VALUES ('kreativitet och improvisation');
INSERT INTO tag (name) VALUES ('utbyte och sammanföring av tekniker');
INSERT INTO tag (name) VALUES ('kondition och uthållighet');
INSERT INTO tag (name) VALUES ('styrka och explosivitet');
INSERT INTO tag (name) VALUES ('rörlighet och smidighet');
INSERT INTO tag (name) VALUES ('flexibilitet');