--
-- INSERTS FOR TECHNIQUES
--
INSERT INTO technique (name, description) VALUES ('Empi uchi, jodan och chudan (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Uraken uchi, jodan (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Yoko geri chudan (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Waki gatame, mot diagonalt grepp, ude osage gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('hiji gatame, gripa, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Seoi nage, mot grepp i ärmen, ude hishigi hiza gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Uki otoshi, mot grepp i ärmen, ude henkan gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude hiza osae gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kata osae (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Nige no kata (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper liggande (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret med två händer och knästöt, Gedan juji uke, waki gatame, kata osae', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen med drag, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp med neddrag, Frigöring, ude henkan gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kragen med höger hand och svingslag, Jodan uchi uke, ude gatame, kata osae', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kragen med vänster hand och svingslag, Jodan uchi uke, o soto otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret mot liggande, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, mellan benen, Juji gatame, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Vända liggande, Vända runt, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Slag mot liggande sittande på magen, Uchi uke, frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju jodan uchi uke, uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju morote jodan uke, waki gatame, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju jodan uchi uke, seoi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, hiji gatame, hara osae', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen och grepp, Grepp, waki gatame, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot bröstet uppifrån, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Pistolhot framifrån, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, grepp i kläderna med svingslag, Jodan uchi uke, yoko geri, kin geri, kote gaeshi, taktisk nedläggning', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret med två händer och knästöt, Gedan juji uke, waki gatame - Koet gaeshi, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen med drag O soto otoshi - Kuzure ude garami, kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag och svingslag, Morote jodan uke - Morote jodan uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, chudan tski - Hiza geri', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, hiji gatame, hara osae - Ushiro osae', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, forehand och backhand, Tsuri ashi - ju jodan uchi uke, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Haito uchi, jodan (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Shuto uchi, jodan, höger och vänster sida (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ude hishigi, gripa (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Kuzure kote gaeshi gatame, gripa (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ude garami, gripa, kote gatame (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Harai goshi, mot grepp i ärmen, ude hishigi hiza gatame (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Sukui nage, mot grepp i ärmen, ude hishigi hiza gatame (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ju-jutsu kai no kat, serie 1 (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med slag och spark (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret bakifrån med neddrag, Shiho nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag från sidan, Harai goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, Sukui nage ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen med neddrag, Ura makikomi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp med neddrag, Frigöring, ude henkan gatame (1Dan svart)', '');
INSERT INTO technique (name, description) VALUES ('Dubbelnelson med nedbrytning, Mae ukemi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i en ärm från sidan, Ude hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till höftkast, O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kragen med neddrag, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Försök till livtag, över armarna, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Vända liggande, Vänd runt, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag mot liggande, Uchi uke, frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Spark mot liggande mot grenen, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Försök till knuff, Irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, sukui nage', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju jodan uchi uke, uki otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot magen med grepp om nacken, Gedan juji uke, ude osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, forehand, Tsuri ashi, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot bröstet från sidan, backhand, Grepp ude garami, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Pistolhot bakifrån, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Försök till knuff, Irimi nage - O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju morote jodan uke, hiki otoshi', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand och forehnad, Tsuri ashi - O soto osae, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot magen med grepp om nacken, Gedan juji uke, ude osae - Ude garami, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Ude hishigi - Kuzure kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Hiji gatame - Ude garami, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Ushiro geri, chudan (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Kuzure ude guruma, gripa (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Okuri ude gatame, gripa (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ju-jutsu Kai no kata serie 1 och 2 (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper liggande (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Tsuri komi, tai otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Te guruma, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen neddrag, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp från sidan, Tani otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp om nacken och knästöt, Gedan juji uke, irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna, O soto gari, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till höftkast, O goshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i en ärm och svingslag, Jodan uchi uke, kuzure ude guruma', '');
INSERT INTO technique (name, description) VALUES ('Försök till livtag över armarna från sidan, Harai goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Nedtryckning från sidan, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till knuff, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Morote jodan uke hiza geri, tai guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Cirkulär spark mot sidan, Gedan uchi uke, o uchi otoshi', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot benen, San ren uke, o soto osae, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen bakifrån, höger arm, Kuzure ude osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen bakifrån, vänster arm, Kuzure ude garami, kote gaeshi', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen sittande mellan benen, Hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till pistolhot, Grepp, shotei uchi, kin geri, o soto osae', '');
INSERT INTO technique (name, description) VALUES ('Ingripa mot slag mot liggande, Nedläggning ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Ingripa mot armstrypning, Irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, knivhot framifrån och svingslag, Grepp, shotei uchi, kin geri, o soto osae', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån och knästöt, Frigöring - Gedan juji uke, irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, gedan mawashi, geri gyaku tski', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, forehand och backhand, Tsuri ashi - Ju jodan uchi uke, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, nackhand och forehand, Tsuri ashi - Grepp, hiza geri, kuzure uda osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Hiji gatame - Okura ude gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Kuzure ude guruma - Hiji gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Kuzure kote gaeshi gatame - Okuri ude gatame', '');
INSERT INTO technique (name, description) VALUES ('Buki no kata (3 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (3 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med påk (3 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag, Kata guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp med neddrag, Yoko guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Tomoe nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till fotsvep, Ko soto gari, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Lågt livtag framifrån med tryck, Sumi gaeshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag undet armarna framifrån med upplyft, Tate hishigi, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna bakifrån med upplyft, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Försök till grepp om båda benen, Tai guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp om ena benet framifrån med lyft, Sumi gaeshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, ovanför huvudet, Juji gatame, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Cirkulär spark mot sidan, Gedan uchi uke, uchi mata', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet med tvåhandsgrepp, Irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkstöt mot magen, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot från sidan, Hiza geri, ude gatame, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot magen, underifrån, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot liggande, sittande på magen, Juji uke, ude osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Ingripa mot grepp i kläderna och svingslag, Irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Ingripande mot knivhot mot liggande, sittande på magen, Nedläggning, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, stryptag mot liggande, Frigöring, kakato geri', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, svingslag och svingslag, Morote jodan uke, hiza geri, tai guruma', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, påkslag forehand, backhand och svingslag, Ju jodan uchi uke, irimi nage, påkslag', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån och kravattgrepp, Kota gaeshi - Tani otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Hot mot liggande och svingslag, Ju jodan uchi uke - Uki otoshi', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, forehand och backhand, Blockering med påk, påkslag', '');
INSERT INTO technique (name, description) VALUES ('Påkslag med huvudet med tvåhandsgrepp, Irimi nage - O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, forehand och backhand, Tsuri ashi - Blockering med påk, påkslag', '');
INSERT INTO technique (name, description) VALUES ('Rak spark mot magen, Blockering med påk - Gripa med påk', '');
INSERT INTO technique (name, description) VALUES ('Gripa liggande, Vända liggande - Kuzure kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Kamae, neutral (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kamae, beredd (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kamae, gard (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ayumi ashi (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Tsuri ashi (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Taisabaki, kort, höger och vänster (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Taisabaki, lång, höger och vänster (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Uppgång bakåt (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ushiro ukemi med dämpning (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ju morote jodan uke, mot svingslag (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Jodan uchi uke, mot rakt slag (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan uchi uke, mot cirkulärt slag (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan juji uke, mot knästöt och rak spark (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Shotei uchi, jodan och chudan (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Me uchi, insidan och utsidan (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan geri (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude osae, mot grepp i ärmen, ude osae gatame (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude osae gatame (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude henkan gatame (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder framifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder bakifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret framifrån, Ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret bakifrån, Tettsui uchi, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen, Kuzure ude osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till kravattgrepp från sidan, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp om nacken och knästöt, Gedan juji uke, frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag, Jodan uchi uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna framifrån, Tate hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna bakifrån, Fumikomi, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande sittande bredvid, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Hot mot liggande, Uppgång bakåt', '');
INSERT INTO technique (name, description) VALUES ('Hotfullt närmande framifrån, Hejda med tryck', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju morote jodan uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju morote jodan uke', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, bakhand, Ju morote jodan uke', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder framifrån och svingslag, Frigöring - Ju morote jodan uke', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån och svingslag, backhand, Frigöring - Ju morote jodan uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Mae ukemi (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ushiro ukemi (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Morote jodan uke, mot svingslag (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Chudan soto uke, mot rakt slag (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan soto uke, mot rak spark (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Chudan tski (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kin geri (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote gaeshi, mot diagonalt grepp, kote gaeshi gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('O soto osae, mot grepp i ärmen, ude henkan gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('O soto otoshi, mot grepp i ärmen, ude hishigi hiza gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude hishigi hiza gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote gaeshi gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder bakifrån, Kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, O soto otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån mot vägg, Tsuri komi, taisabaki', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med vänster arm, Kuzure ude garami, kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp från sidan, Ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till grepp i kläderna, Chudan soto uke', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Kuzure ude garami, ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med drag, O soto otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag över armarna framifrån, O soto otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp om båda benen framifrån, Tate hishigi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, mellan benen, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Morote jodan uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju morote jodan uke, hiki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rak spark mot magen, Gedan soto uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju morote jodan uke, hiki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen, vänster sida, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen, höger sida, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, o soto otoshi - Kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån mot vägg, Tsuri komi - Ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju morote jodan uke, hiki otoshi - O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder framifrån, Shiho nage, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder underifrån,Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag, Jodan soto uke', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Tsuri komi, o goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, O soto otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag, Jodan uchi uke, o soto otoshi, ude henkan gatame ', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna bakifrån, Hiza osae', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag mot liggande, Uchi uke, hiza kansetsu wasa', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju jodan uchi uke, shiho nage, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju morote jodan uke, kote gaeshi, kote gaeshi gatame', ' ');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Morote jodan uke, ko soto gari, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rak slag mot magen, Gedan uchi uke, ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju jodan uchi uke, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Påksalg mot huvudet, backhand, Ju morote jodan uke, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot magen, Grepp, kin geri, kote  gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, grepp i kläderna, Ude osae, taktisk nedläggning', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, O soto otoshi - Kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag, Jodan uchi uke, o soto otoshi - Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, o soto otoshi - Kin geri, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('mae ukemi med dämpning (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Jodan soto uke, mot slag (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('San ren uke, mot cirkulär spark (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kizami tski, jodan och chudan (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('mae geri, chudan (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote mawashi, mot grepp i ärmen, kote mawashi gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Shihi nage, mot diagonalt grepp, shiho nage gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ko soto gari, mot grepp i ärmen, ude hishigi hiza gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('O goshi, mot grepp i ärmen, ude hishigi hiza gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('kote mawashi gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Shiho nage gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES (' Randori mot en motståndare (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Otoshi ukemi (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Chudan uchi uke, mot rakt slag (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gyaku tski, chudan (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Hiza geri, chudan (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Mawashi geri, chudan och gedan (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote hineri, mot diagonalt grepp, ude henkan gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Irimi nage, mot diagonalt grepp, ude henkan gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ko uchi gari, mot grepp i ärmen, ude hishigi hiza gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med slag och spark (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Stryptag från sidan med tryck, Kote hineri, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen och en arm på ryggen, O soto otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp framifrån, Chudan tski, kote hineri, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till grepp i kläderna, Chudan uchi uke, ko soto gari, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna mot vägg, Tate hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag över armarna framifrån, O goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag över armarna bakifrån, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, mellan benen, Frigöring, kakato geri', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen mot liggande, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag mot liggande, Tate hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Spark mot liggande, mot huvudet, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Morote jodan uke, ko uchi gari, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju jodan uchi uke, irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Cirkulär spark mot huvudet, San ren uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju jorda uchi uke, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivstick mot magen, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, svingslag och grepp i kläderna, Jodan uchi uke, mae geri, kote mawashi, taktisk nedläggning', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret framifrån, ude osae - Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen och en arm på ryggen, O soto otoshi - Kuzure ude garami, kote gaeshi, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot magen, Chudan uchi uke, gyaku tski - Mawashi geri', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju jodan uchi uke, irimi nage - Ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (4 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med kniv(4 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Goshin jutsu no kata (4 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Kime no kata (5 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (5 Dan)', '');



--
-- INSERTS FOR TECHNIQUES TO BELT
--

INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 1);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 2);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 3);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 4);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 5);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 6);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 7);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 8);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 9);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 10);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 11);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 12);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 13);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 14);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 15);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 16);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 17);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 18);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 19);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 20);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 21);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 22);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 23);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 24);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 25);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 26);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 27);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 28);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 29);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 30);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 31);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 32);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 33);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 34);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 35);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 36);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 37);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 38);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 39);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 40);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 41);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 42);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 43);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 44);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 45);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 46);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 47);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 48);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 49);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 50);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 51);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 52);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 53);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 54);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 55);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 56);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 57);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 58);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 59);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 60);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 61);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 62);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 63);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 64);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 65);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 66);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 67);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 68);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 69);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 70);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 71);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 72);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 73);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 74);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 75);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 76);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 77);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 78);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 79);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 80);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 81);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 82);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 83);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 84);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 85);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 86);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 87);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 88);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 89);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 90);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 91);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 92);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 93);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 94);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 95);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 96);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 97);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 98);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 99);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 100);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 101);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 102);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 103);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 104);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 105);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 106);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 107);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 108);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 109);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 110);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 111);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 112);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 113);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 114);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 115);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 116);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 117);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 118);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 119);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 120);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 121);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 122);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 123);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 124);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 125);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 126);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 127);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 128);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 129);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 130);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 131);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 132);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 133);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 134);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 135);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 136);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 137);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 138);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 139);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 140);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 141);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 142);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 143);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 144);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 145);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 146);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 147);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 148);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 149);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 150);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 151);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 152);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 153);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 154);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 155);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 156);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 157);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 158);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 159);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 160);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 161);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 162);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 163);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 164);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 165);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 166);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 167);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 168);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 169);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 170);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 171);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 172);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 173);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 174);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 175);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 176);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 177);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 178);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 179);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 180);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 181);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 182);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 183);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 184);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 185);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 186);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 187);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 188);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 189);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 190);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 191);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 192);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 193);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 194);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 195);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 196);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 197);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 198);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 199);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 200);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 201);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 202);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 203);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 204);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 205);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 206);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 207);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 208);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 209);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 210);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 211);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 212);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 213);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 214);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 215);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 216);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 217);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 218);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 219);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 220);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 221);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 222);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 223);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 224);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 225);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 226);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 227);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 228);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 229);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 230);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 231);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 232);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 233);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 234);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 235);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 236);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 237);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 238);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 239);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 240);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 241);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 242);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 243);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 244);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 245);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 246);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 247);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 248);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 249);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 250);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 251);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 252);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 253);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 254);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 255);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 256);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 257);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 258);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 259);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 260);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 261);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 262);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 263);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 264);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 265);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 266);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 267);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 268);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 269);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 270);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 271);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 272);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 273);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 274);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 275);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 276);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 277);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 278);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 279);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 280);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 281);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 282);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 283);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 284);
--
-- INSERTS FOR TECHNIQUES TAG
--

INSERT INTO technique_tag (tech_id, tag_id) VALUES (1, 4), (1, 42), (1, 26);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (2, 60), (2, 5), (2, 12);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (3, 48), (3, 73), (3, 23);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (4, 91), (4, 74), (4, 2);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (5, 60), (5, 42), (5, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (6, 46), (6, 1), (6, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (7, 58), (7, 49), (7, 42);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (8, 90), (8, 1), (8, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (9, 62), (9, 44), (9, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (10, 61), (10, 8), (10, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (11, 46), (11, 19), (11, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (12, 31), (12, 27), (12, 56);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (13, 4), (13, 15), (13, 34);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (14, 70), (14, 47), (14, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (15, 87), (15, 73), (15, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (16, 49), (16, 6), (16, 70);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (17, 21), (17, 84), (17, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (18, 90), (18, 72), (18, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (19, 62), (19, 9), (19, 79);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (20, 80), (20, 15), (20, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (21, 32), (21, 6), (21, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (22, 22), (22, 65), (22, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (23, 39), (23, 74), (23, 19);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (24, 11), (24, 51), (24, 92);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (25, 6), (25, 45), (25, 88);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (26, 70), (26, 25), (26, 74);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (27, 1), (27, 16), (27, 92);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (28, 78), (28, 82), (28, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (29, 49), (29, 53), (29, 90);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (30, 1), (30, 89), (30, 28);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (31, 48), (31, 18), (31, 74);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (32, 26), (32, 32), (32, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (33, 74), (33, 25), (33, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (34, 63), (34, 52), (34, 59);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (35, 1), (35, 8), (35, 7);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (36, 59), (36, 1), (36, 31);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (37, 31), (37, 18), (37, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (38, 5), (38, 88), (38, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (39, 7), (39, 66), (39, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (40, 36), (40, 55), (40, 75);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (41, 41), (41, 54), (41, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (42, 1), (42, 42), (42, 88);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (43, 10), (43, 72), (43, 43);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (44, 85), (44, 49), (44, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (45, 32), (45, 67), (45, 27);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (46, 51), (46, 59), (46, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (47, 39), (47, 42), (47, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (48, 61), (48, 40), (48, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (49, 24), (49, 1), (49, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (50, 24), (50, 3), (50, 43);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (51, 1), (51, 82), (51, 16);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (52, 79), (52, 52), (52, 39);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (53, 1), (53, 23), (53, 13);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (54, 20), (54, 79), (54, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (55, 45), (55, 28), (55, 74);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (56, 85), (56, 22), (56, 19);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (57, 27), (57, 75), (57, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (58, 1), (58, 18), (58, 88);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (59, 8), (59, 1), (59, 23);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (60, 8), (60, 4), (60, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (61, 42), (61, 2), (61, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (62, 73), (62, 48), (62, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (63, 44), (63, 67), (63, 87);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (64, 85), (64, 35), (64, 93);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (65, 90), (65, 58), (65, 85);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (66, 79), (66, 35), (66, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (67, 1), (67, 17), (67, 78);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (68, 87), (68, 70), (68, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (69, 22), (69, 64), (69, 36);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (70, 78), (70, 1), (70, 43);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (71, 21), (71, 55), (71, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (72, 80), (72, 23), (72, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (73, 60), (73, 24), (73, 31);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (74, 18), (74, 86), (74, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (75, 27), (75, 87), (75, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (76, 88), (76, 35), (76, 11);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (77, 50), (77, 86), (77, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (78, 40), (78, 30), (78, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (79, 71), (79, 56), (79, 9);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (80, 47), (80, 46), (80, 39);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (81, 9), (81, 88), (81, 28);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (82, 13), (82, 1), (82, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (83, 33), (83, 65), (83, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (84, 1), (84, 79), (84, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (85, 1), (85, 22), (85, 47);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (86, 1), (86, 91), (86, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (87, 45), (87, 93), (87, 34);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (88, 51), (88, 30), (88, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (89, 47), (89, 1), (89, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (90, 6), (90, 65), (90, 34);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (91, 36), (91, 69), (91, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (92, 1), (92, 48), (92, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (93, 61), (93, 10), (93, 66);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (94, 1), (94, 67), (94, 42);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (95, 49), (95, 11), (95, 36);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (96, 9), (96, 1), (96, 11);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (97, 61), (97, 91), (97, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (98, 57), (98, 80), (98, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (99, 32), (99, 4), (99, 93);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (100, 41), (100, 36), (100, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (101, 82), (101, 66), (101, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (102, 1), (102, 85), (102, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (103, 2), (103, 30), (103, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (104, 31), (104, 57), (104, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (105, 16), (105, 77), (105, 13);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (106, 1), (106, 84), (106, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (107, 24), (107, 21), (107, 93);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (108, 69), (108, 43), (108, 47);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (109, 64), (109, 13), (109, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (110, 36), (110, 70), (110, 2);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (111, 82), (111, 1), (111, 48);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (112, 87), (112, 7), (112, 93);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (113, 82), (113, 27), (113, 28);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (114, 79), (114, 22), (114, 70);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (115, 63), (115, 16), (115, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (116, 2), (116, 68), (116, 47);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (117, 9), (117, 84), (117, 79);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (118, 73), (118, 86), (118, 21);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (119, 82), (119, 54), (119, 5);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (120, 33), (120, 82), (120, 45);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (121, 73), (121, 37), (121, 13);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (122, 1), (122, 62), (122, 9);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (123, 5), (123, 21), (123, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (124, 88), (124, 52), (124, 3);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (125, 43), (125, 76), (125, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (126, 1), (126, 82), (126, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (127, 47), (127, 65), (127, 91);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (128, 2), (128, 78), (128, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (129, 24), (129, 1), (129, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (130, 44), (130, 1), (130, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (131, 85), (131, 55), (131, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (132, 32), (132, 1), (132, 42);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (133, 90), (133, 23), (133, 60);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (134, 57), (134, 32), (134, 24);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (135, 48), (135, 86), (135, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (136, 8), (136, 27), (136, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (137, 3), (137, 1), (137, 46);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (138, 11), (138, 67), (138, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (139, 1), (139, 89), (139, 91);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (140, 38), (140, 49), (140, 87);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (141, 57), (141, 60), (141, 47);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (142, 31), (142, 86), (142, 38);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (143, 51), (143, 1), (143, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (144, 71), (144, 1), (144, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (145, 66), (145, 48), (145, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (146, 44), (146, 73), (146, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (147, 8), (147, 72), (147, 75);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (148, 21), (148, 28), (148, 5);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (149, 85), (149, 1), (149, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (150, 43), (150, 56), (150, 75);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (151, 12), (151, 75), (151, 66);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (152, 1), (152, 18), (152, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (153, 74), (153, 36), (153, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (154, 27), (154, 60), (154, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (155, 13), (155, 83), (155, 55);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (156, 51), (156, 91), (156, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (157, 23), (157, 39), (157, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (158, 19), (158, 27), (158, 26);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (159, 38), (159, 53), (159, 7);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (160, 3), (160, 92), (160, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (161, 82), (161, 10), (161, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (162, 76), (162, 77), (162, 73);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (163, 89), (163, 11), (163, 16);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (164, 7), (164, 65), (164, 53);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (165, 2), (165, 1), (165, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (166, 81), (166, 20), (166, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (167, 1), (167, 18), (167, 81);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (168, 2), (168, 22), (168, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (169, 88), (169, 62), (169, 9);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (170, 86), (170, 35), (170, 24);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (171, 31), (171, 41), (171, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (172, 1), (172, 19), (172, 88);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (173, 35), (173, 49), (173, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (174, 61), (174, 70), (174, 53);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (175, 46), (175, 44), (175, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (176, 5), (176, 78), (176, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (177, 1), (177, 71), (177, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (178, 54), (178, 60), (178, 87);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (179, 7), (179, 67), (179, 70);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (180, 87), (180, 34), (180, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (181, 81), (181, 24), (181, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (182, 14), (182, 26), (182, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (183, 62), (183, 21), (183, 17);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (184, 84), (184, 69), (184, 3);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (185, 52), (185, 21), (185, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (186, 32), (186, 83), (186, 45);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (187, 32), (187, 56), (187, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (188, 69), (188, 26), (188, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (189, 5), (189, 81), (189, 46);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (190, 8), (190, 28), (190, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (191, 19), (191, 17), (191, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (192, 70), (192, 15), (192, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (193, 57), (193, 14), (193, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (194, 30), (194, 15), (194, 34);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (195, 38), (195, 57), (195, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (196, 50), (196, 72), (196, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (197, 87), (197, 26), (197, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (198, 68), (198, 93), (198, 72);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (199, 1), (199, 93), (199, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (200, 15), (200, 27), (200, 17);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (201, 10), (201, 54), (201, 26);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (202, 8), (202, 92), (202, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (203, 65), (203, 9), (203, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (204, 63), (204, 12), (204, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (205, 62), (205, 25), (205, 59);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (206, 90), (206, 75), (206, 70);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (207, 29), (207, 17), (207, 13);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (208, 53), (208, 50), (208, 35);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (209, 20), (209, 45), (209, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (210, 27), (210, 26), (210, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (211, 70), (211, 13), (211, 92);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (212, 8), (212, 30), (212, 6);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (213, 7), (213, 1), (213, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (214, 7), (214, 76), (214, 36);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (215, 63), (215, 86), (215, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (216, 65), (216, 1), (216, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (217, 50), (217, 72), (217, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (218, 56), (218, 80), (218, 7);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (219, 8), (219, 18), (219, 42);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (220, 1), (220, 39), (220, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (221, 4), (221, 56), (221, 90);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (222, 1), (222, 78), (222, 48);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (223, 28), (223, 38), (223, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (224, 45), (224, 20), (224, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (225, 21), (225, 76), (225, 20);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (226, 89), (226, 82), (226, 92);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (227, 63), (227, 57), (227, 23);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (228, 38), (228, 91), (228, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (229, 38), (229, 1), (229, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (230, 1), (230, 39), (230, 55);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (231, 2), (231, 78), (231, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (232, 48), (232, 74), (232, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (233, 37), (233, 27), (233, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (234, 74), (234, 1), (234, 23);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (235, 56), (235, 9), (235, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (236, 25), (236, 1), (236, 39);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (237, 90), (237, 54), (237, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (238, 68), (238, 5), (238, 4);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (239, 12), (239, 91), (239, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (240, 6), (240, 32), (240, 67);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (241, 70), (241, 22), (241, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (242, 12), (242, 86), (242, 75);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (243, 66), (243, 16), (243, 85);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (244, 18), (244, 15), (244, 9);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (245, 55), (245, 48), (245, 66);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (246, 19), (246, 93), (246, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (247, 27), (247, 10), (247, 16);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (248, 93), (248, 29), (248, 34);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (249, 29), (249, 26), (249, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (250, 68), (250, 83), (250, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (251, 1), (251, 27), (251, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (252, 7), (252, 30), (252, 6);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (253, 1), (253, 17), (253, 23);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (254, 29), (254, 1), (254, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (255, 11), (255, 1), (255, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (256, 42), (256, 38), (256, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (257, 93), (257, 10), (257, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (258, 62), (258, 16), (258, 84);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (259, 39), (259, 1), (259, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (260, 51), (260, 28), (260, 2);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (261, 38), (261, 15), (261, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (262, 92), (262, 35), (262, 91);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (263, 5), (263, 59), (263, 31);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (264, 47), (264, 4), (264, 2);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (265, 1), (265, 26), (265, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (266, 3), (266, 1), (266, 66);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (267, 33), (267, 16), (267, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (268, 40), (268, 69), (268, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (269, 24), (269, 41), (269, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (270, 20), (270, 64), (270, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (271, 1), (271, 68), (271, 67);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (272, 32), (272, 42), (272, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (273, 62), (273, 78), (273, 47);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (274, 5), (274, 87), (274, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (275, 72), (275, 69), (275, 3);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (276, 13), (276, 18), (276, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (277, 64), (277, 56), (277, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (278, 29), (278, 4), (278, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (279, 13), (279, 58), (279, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (280, 91), (280, 7), (280, 3);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (281, 51), (281, 38), (281, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (282, 12), (282, 24), (282, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (283, 8), (283, 88), (283, 85);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (284, 1), (284, 68), (284, 88);