--
-- INSERTS FOR TECHNIQUES
--
INSERT INTO technique (name, description) VALUES ('Empi uchi, jodan och chudan (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Uraken uchi, jodan (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Yoko geri chudan (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Waki gatame, mot diagonalt grepp, ude osage gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('hiji gatame, gripa, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Seoi nage, mot grepp i ärmen, ude hishigi hiza gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Uki otoshi, mot grepp i ärmen, ude henkan gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude hiza osae gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kata osae (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Nige no kata (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper liggande (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret med två händer och knästöt, Gedan juji uke, waki gatame, kata osae', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen med drag, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp med neddrag, Frigöring, ude henkan gatame (1 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kragen med höger hand och svingslag, Jodan uchi uke, ude gatame, kata osae', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kragen med vänster hand och svingslag, Jodan uchi uke, o soto otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret mot liggande, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, mellan benen, Juji gatame, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Vända liggande, Vända runt, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Slag mot liggande sittande på magen, Uchi uke, frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju jodan uchi uke, uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju morote jodan uke, waki gatame, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju jodan uchi uke, seoi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, hiji gatame, hara osae', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen och grepp, Grepp, waki gatame, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot bröstet uppifrån, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Pistolhot framifrån, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, grepp i kläderna med svingslag, Jodan uchi uke, yoko geri, kin geri, kote gaeshi, taktisk nedläggning', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret med två händer och knästöt, Gedan juji uke, waki gatame - Koet gaeshi, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen med drag O soto otoshi - Kuzure ude garami, kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag och svingslag, Morote jodan uke - Morote jodan uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, chudan tski - Hiza geri', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, hiji gatame, hara osae - Ushiro osae', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, forehand och backhand, Tsuri ashi - ju jodan uchi uke, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Haito uchi, jodan (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Shuto uchi, jodan, höger och vänster sida (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ude hishigi, gripa (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Kuzure kote gaeshi gatame, gripa (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ude garami, gripa, kote gatame (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Harai goshi, mot grepp i ärmen, ude hishigi hiza gatame (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Sukui nage, mot grepp i ärmen, ude hishigi hiza gatame (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ju-jutsu kai no kat, serie 1 (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med slag och spark (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (1 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret bakifrån med neddrag, Shiho nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag från sidan, Harai goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, Sukui nage ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen med neddrag, Ura makikomi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp med neddrag, Frigöring, ude henkan gatame (1Dan svart)', '');
INSERT INTO technique (name, description) VALUES ('Dubbelnelson med nedbrytning, Mae ukemi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i en ärm från sidan, Ude hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till höftkast, O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kragen med neddrag, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Försök till livtag, över armarna, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Vända liggande, Vänd runt, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag mot liggande, Uchi uke, frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Spark mot liggande mot grenen, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Försök till knuff, Irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, sukui nage', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju jodan uchi uke, uki otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot magen med grepp om nacken, Gedan juji uke, ude osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, forehand, Tsuri ashi, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot bröstet från sidan, backhand, Grepp ude garami, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Pistolhot bakifrån, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Försök till knuff, Irimi nage - O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju morote jodan uke, hiki otoshi', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand och forehnad, Tsuri ashi - O soto osae, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot magen med grepp om nacken, Gedan juji uke, ude osae - Ude garami, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Ude hishigi - Kuzure kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Hiji gatame - Ude garami, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Ushiro geri, chudan (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Kuzure ude guruma, gripa (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Okuri ude gatame, gripa (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Ju-jutsu Kai no kata serie 1 och 2 (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper liggande (2 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Tsuri komi, tai otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Te guruma, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen neddrag, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp från sidan, Tani otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp om nacken och knästöt, Gedan juji uke, irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna, O soto gari, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till höftkast, O goshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i en ärm och svingslag, Jodan uchi uke, kuzure ude guruma', '');
INSERT INTO technique (name, description) VALUES ('Försök till livtag över armarna från sidan, Harai goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Nedtryckning från sidan, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till knuff, Uki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Morote jodan uke hiza geri, tai guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Cirkulär spark mot sidan, Gedan uchi uke, o uchi otoshi', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot benen, San ren uke, o soto osae, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen bakifrån, höger arm, Kuzure ude osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen bakifrån, vänster arm, Kuzure ude garami, kote gaeshi', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen sittande mellan benen, Hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till pistolhot, Grepp, shotei uchi, kin geri, o soto osae', '');
INSERT INTO technique (name, description) VALUES ('Ingripa mot slag mot liggande, Nedläggning ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Ingripa mot armstrypning, Irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, knivhot framifrån och svingslag, Grepp, shotei uchi, kin geri, o soto osae', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån och knästöt, Frigöring - Gedan juji uke, irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, gedan mawashi, geri gyaku tski', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, forehand och backhand, Tsuri ashi - Ju jodan uchi uke, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, nackhand och forehand, Tsuri ashi - Grepp, hiza geri, kuzure uda osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Hiji gatame - Okura ude gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Kuzure ude guruma - Hiji gatame', '');
INSERT INTO technique (name, description) VALUES ('Gripa stående, Kuzure kote gaeshi gatame - Okuri ude gatame', '');
INSERT INTO technique (name, description) VALUES ('Buki no kata (3 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (3 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med påk (3 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag, Kata guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp med neddrag, Yoko guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Tomoe nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till fotsvep, Ko soto gari, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Lågt livtag framifrån med tryck, Sumi gaeshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag undet armarna framifrån med upplyft, Tate hishigi, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna bakifrån med upplyft, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Försök till grepp om båda benen, Tai guruma, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp om ena benet framifrån med lyft, Sumi gaeshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, ovanför huvudet, Juji gatame, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Cirkulär spark mot sidan, Gedan uchi uke, uchi mata', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet med tvåhandsgrepp, Irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkstöt mot magen, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot från sidan, Hiza geri, ude gatame, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot magen, underifrån, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhugg mot liggande, sittande på magen, Juji uke, ude osae, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Ingripa mot grepp i kläderna och svingslag, Irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Ingripande mot knivhot mot liggande, sittande på magen, Nedläggning, ude hiza osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, stryptag mot liggande, Frigöring, kakato geri', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, svingslag och svingslag, Morote jodan uke, hiza geri, tai guruma', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, påkslag forehand, backhand och svingslag, Ju jodan uchi uke, irimi nage, påkslag', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån och kravattgrepp, Kota gaeshi - Tani otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Hot mot liggande och svingslag, Ju jodan uchi uke - Uki otoshi', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, forehand och backhand, Blockering med påk, påkslag', '');
INSERT INTO technique (name, description) VALUES ('Påkslag med huvudet med tvåhandsgrepp, Irimi nage - O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivskärning, forehand och backhand, Tsuri ashi - Blockering med påk, påkslag', '');
INSERT INTO technique (name, description) VALUES ('Rak spark mot magen, Blockering med påk - Gripa med påk', '');
INSERT INTO technique (name, description) VALUES ('Gripa liggande, Vända liggande - Kuzure kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Kamae, neutral (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kamae, beredd (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kamae, gard (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ayumi ashi (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Tsuri ashi (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Taisabaki, kort, höger och vänster (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Taisabaki, lång, höger och vänster (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Uppgång bakåt (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ushiro ukemi med dämpning (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ju morote jodan uke, mot svingslag (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Jodan uchi uke, mot rakt slag (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan uchi uke, mot cirkulärt slag (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan juji uke, mot knästöt och rak spark (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Shotei uchi, jodan och chudan (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Me uchi, insidan och utsidan (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan geri (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude osae, mot grepp i ärmen, ude osae gatame (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude osae gatame (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude henkan gatame (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (5 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder framifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder bakifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret framifrån, Ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret bakifrån, Tettsui uchi, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen, Kuzure ude osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till kravattgrepp från sidan, Frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp om nacken och knästöt, Gedan juji uke, frigöring', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag, Jodan uchi uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna framifrån, Tate hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna bakifrån, Fumikomi, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande sittande bredvid, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Hot mot liggande, Uppgång bakåt', '');
INSERT INTO technique (name, description) VALUES ('Hotfullt närmande framifrån, Hejda med tryck', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju morote jodan uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju morote jodan uke', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, bakhand, Ju morote jodan uke', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder framifrån och svingslag, Frigöring - Ju morote jodan uke', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån och svingslag, backhand, Frigöring - Ju morote jodan uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Mae ukemi (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ushiro ukemi (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Morote jodan uke, mot svingslag (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Chudan soto uke, mot rakt slag (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gedan soto uke, mot rak spark (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Chudan tski (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kin geri (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote gaeshi, mot diagonalt grepp, kote gaeshi gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('O soto osae, mot grepp i ärmen, ude henkan gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('O soto otoshi, mot grepp i ärmen, ude hishigi hiza gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ude hishigi hiza gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote gaeshi gatame (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (4 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder bakifrån, Kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, O soto otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån mot vägg, Tsuri komi, taisabaki', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med vänster arm, Kuzure ude garami, kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp från sidan, Ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till grepp i kläderna, Chudan soto uke', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Kuzure ude garami, ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med drag, O soto otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag över armarna framifrån, O soto otoshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp om båda benen framifrån, Tate hishigi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, mellan benen, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Morote jodan uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju morote jodan uke, hiki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rak spark mot magen, Gedan soto uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju morote jodan uke, hiki otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen, vänster sida, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot halsen, höger sida, Grepp, kin geri', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, o soto otoshi - Kote gaeshi, kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån mot vägg, Tsuri komi - Ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju morote jodan uke, hiki otoshi - O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder framifrån, Shiho nage, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i två handleder underifrån,Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till stryptag, Jodan soto uke', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, O soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag framifrån, Tsuri komi, o goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, O soto otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna med tryck, Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag, Jodan uchi uke, o soto otoshi, ude henkan gatame ', '');
INSERT INTO technique (name, description) VALUES ('Livtag under armarna bakifrån, Hiza osae', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag mot liggande, Uchi uke, hiza kansetsu wasa', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, Ju jodan uchi uke, shiho nage, shiho nage gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju morote jodan uke, kote gaeshi, kote gaeshi gatame', ' ');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Morote jodan uke, ko soto gari, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Jodan soto uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Rak slag mot magen, Gedan uchi uke, ushiro osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, Ju jodan uchi uke, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Påksalg mot huvudet, backhand, Ju morote jodan uke, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivhot mot magen, Grepp, kin geri, kote  gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, grepp i kläderna, Ude osae, taktisk nedläggning', '');
INSERT INTO technique (name, description) VALUES ('Stryptag bakifrån, O soto otoshi - Kote gaeshi gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna och svingslag, Jodan uchi uke, o soto otoshi - Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju morote jodan uke, o soto otoshi - Kin geri, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('mae ukemi med dämpning (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Jodan soto uke, mot slag (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('San ren uke, mot cirkulär spark (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kizami tski, jodan och chudan (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('mae geri, chudan (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote mawashi, mot grepp i ärmen, kote mawashi gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Shihi nage, mot diagonalt grepp, shiho nage gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ko soto gari, mot grepp i ärmen, ude hishigi hiza gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('O goshi, mot grepp i ärmen, ude hishigi hiza gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('kote mawashi gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Shiho nage gatame (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES (' Randori mot en motståndare (3 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Otoshi ukemi (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Chudan uchi uke, mot rakt slag (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Gyaku tski, chudan (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Hiza geri, chudan (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Mawashi geri, chudan och gedan (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote hineri, mot diagonalt grepp, ude henkan gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Irimi nage, mot diagonalt grepp, ude henkan gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Ko uchi gari, mot grepp i ärmen, ude hishigi hiza gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Kote gatame (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med slag och spark (2 Kyu)', '');
INSERT INTO technique (name, description) VALUES ('Stryptag från sidan med tryck, Kote hineri, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen och en arm på ryggen, O soto otoshi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Kravattgrepp framifrån, Chudan tski, kote hineri, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Försök till grepp i kläderna, Chudan uchi uke, ko soto gari, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Grepp i kläderna mot vägg, Tate hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag över armarna framifrån, O goshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag över armarna bakifrån, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Stryptag mot liggande, mellan benen, Frigöring, kakato geri', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen mot liggande, Frigöring, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Livtag mot liggande, Tate hishigi, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Spark mot liggande, mot huvudet, Hiza kansetsu waza', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot huvudet, Morote jodan uke, ko uchi gari, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Svingslag, backhand, Ju jodan uchi uke, irimi nage, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Cirkulär spark mot huvudet, San ren uke, o soto osae, ude henkan gatame', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju jorda uchi uke, irimi nage, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Knivstick mot magen, Grepp, kote gaeshi, ude hishigi hiza gatame', '');
INSERT INTO technique (name, description) VALUES ('Två motståndare, svingslag och grepp i kläderna, Jodan uchi uke, mae geri, kote mawashi, taktisk nedläggning', '');
INSERT INTO technique (name, description) VALUES ('Grepp i håret framifrån, ude osae - Kote mawashi, kote mawashi gatame', '');
INSERT INTO technique (name, description) VALUES ('Stryptag med armen och en arm på ryggen, O soto otoshi - Kuzure ude garami, kote gaeshi, kote gatame', '');
INSERT INTO technique (name, description) VALUES ('Rakt slag mot magen, Chudan uchi uke, gyaku tski - Mawashi geri', '');
INSERT INTO technique (name, description) VALUES ('Påkslag mot huvudet, backhand, Ju jodan uchi uke, irimi nage - Ude osae, ude osae gatame', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (4 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot en motståndare som angriper med kniv(4 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Goshin jutsu no kata (4 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Kime no kata (5 Dan)', '');
INSERT INTO technique (name, description) VALUES ('Randori mot två motståndare (5 Dan)', '');



--
-- INSERTS FOR TECHNIQUES TO BELT
--

INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 1);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 2);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 3);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 4);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 5);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 6);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 7);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 8);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 9);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 10);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 11);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 12);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 13);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 14);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 15);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 16);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 17);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 18);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 19);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 20);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 21);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 22);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 23);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 24);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 25);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 26);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 27);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 28);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 29);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 30);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 31);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 32);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 33);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 34);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 35);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (11, 36);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 37);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 38);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 39);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 40);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 41);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 42);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 43);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 44);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 45);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 46);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 47);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 48);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 49);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 50);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 51);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 52);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 53);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 54);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 55);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 56);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 57);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 58);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 59);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 60);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 61);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 62);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 63);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 64);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 65);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 66);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 67);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 68);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 69);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 70);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 71);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 72);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 73);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 74);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 75);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 76);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 77);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 78);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 79);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 80);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 81);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 82);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 83);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 84);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 85);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 86);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 87);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 88);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 89);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 90);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 91);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 92);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 93);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 94);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 95);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 96);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 97);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 98);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 99);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 100);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 101);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 102);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 103);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 104);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 105);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 106);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 107);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 108);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 109);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 110);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 111);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 112);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 113);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 114);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 115);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 116);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 117);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 118);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 119);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 120);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 121);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 122);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 123);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 124);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 125);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 126);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 127);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 128);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 129);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 130);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 131);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 132);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 133);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 134);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 135);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 136);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 137);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 138);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 139);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 140);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 141);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 142);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 143);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 144);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 145);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 146);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 147);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 148);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 149);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 150);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 151);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 152);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 153);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 154);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 155);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 156);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 157);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 158);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 159);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 160);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 161);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 162);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 163);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 164);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 165);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 166);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 167);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 168);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 169);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 170);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 171);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 172);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 173);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 174);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 175);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 176);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 177);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (3, 178);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 179);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 180);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 181);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 182);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 183);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 184);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 185);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 186);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 187);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 188);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 189);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 190);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 191);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 192);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 193);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 194);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 195);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 196);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 197);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 198);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 199);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 200);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 201);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 202);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 203);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 204);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 205);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 206);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 207);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 208);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 209);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 210);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 211);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 212);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (5, 213);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 214);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 215);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 216);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 217);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 218);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 219);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 220);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 221);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 222);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 223);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 224);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 225);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 226);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 227);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 228);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 229);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 230);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 231);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 232);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 233);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 234);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 235);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 236);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 237);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 238);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 239);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 240);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 241);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 242);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 243);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 244);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 245);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 246);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (7, 247);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 248);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 249);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 250);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 251);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 252);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 253);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 254);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 255);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 256);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 257);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 258);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 259);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 260);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 261);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 262);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 263);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 264);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 265);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 266);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 267);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 268);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 269);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 270);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 271);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 272);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 273);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 274);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 275);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 276);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 277);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 278);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (9, 279);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 280);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 281);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 282);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 283);
INSERT INTO technique_to_belt (belt_id, technique_id) VALUES (13, 284);
--
-- INSERTS FOR TECHNIQUES TAG
--

INSERT INTO technique_tag (tech_id, tag_id) VALUES (1, 38), (1, 52), (1, 65);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (2, 19), (2, 43), (2, 76);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (3, 57), (3, 14), (3, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (4, 82), (4, 29), (4, 53);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (5, 14), (5, 88), (5, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (6, 68), (6, 42), (6, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (7, 11), (7, 64), (7, 24);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (8, 45), (8, 87), (8, 16);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (9, 27), (9, 51), (9, 93);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (10, 79), (10, 15), (10, 39);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (11, 3), (11, 66), (11, 19);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (12, 54), (12, 25), (12, 70);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (13, 12), (13, 63), (13, 85);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (14, 61), (14, 77), (14, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (15, 35), (15, 48), (15, 75);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (16, 22), (16, 55), (16, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (17, 78), (17, 94), (17, 21);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (18, 41), (18, 59), (18, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (19, 76), (19, 20), (19, 37);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (20, 8), (20, 42), (20, 67);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (21, 63), (21, 90), (21, 26);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (22, 31), (22, 84), (22, 13);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (23, 72), (23, 23), (23, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (24, 56), (24, 81), (24, 46);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (25, 9), (25, 49), (25, 74);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (26, 47), (26, 73), (26, 17);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (27, 39), (27, 58), (27, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (28, 91), (28, 36), (28, 60);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (29, 16), (29, 33), (29, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (30, 42), (30, 69), (30, 28);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (31, 73), (31, 47), (31, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (32, 18), (32, 35), (32, 92);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (33, 87), (33, 54), (33, 78);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (34, 25), (34, 41), (34, 66);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (35, 53), (35, 89), (35, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (36, 4), (36, 60), (36, 87);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (37, 65), (37, 83), (37, 11);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (38, 33), (38, 56), (38, 84);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (39, 70), (39, 85), (39, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (40, 51), (40, 74), (40, 43);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (41, 1), (41, 27), (41, 64);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (42, 86), (42, 13), (42, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (43, 20), (43, 36), (43, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (44, 55), (44, 82), (44, 45);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (45, 10), (45, 57), (45, 88);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (46, 80), (46, 26), (46, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (47, 37), (47, 65), (47, 91);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (48, 69), (48, 17), (48, 34);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (49, 92), (49, 34), (49, 58);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (50, 15), (50, 40), (50, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (51, 43), (51, 61), (51, 32);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (52, 74), (52, 91), (52, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (53, 27), (53, 44), (53, 79);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (54, 81), (54, 7), (54, 28);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (55, 36), (55, 62), (55, 90);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (56, 23), (56, 39), (56, 55);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (57, 5), (57, 21), (57, 46);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (58, 19), (58, 49), (58, 84);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (59, 45), (59, 75), (59, 91);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (60, 2), (60, 55), (60, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (61, 64), (61, 33), (61, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (62, 17), (62, 42), (62, 73);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (63, 56), (63, 88), (63, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (64, 11), (64, 37), (64, 76);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (65, 38), (65, 63), (65, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (66, 74), (66, 21), (66, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (67, 39), (67, 65), (67, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (68, 57), (68, 5), (68, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (69, 28), (69, 53), (69, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (70, 86), (70, 14), (70, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (71, 32), (71, 58), (71, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (72, 64), (72, 23), (72, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (73, 9), (73, 46), (73, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (74, 47), (74, 93), (74, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (75, 35), (75, 59), (75, 94);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (76, 82), (76, 31), (76, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (77, 56), (77, 81), (77, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (78, 3), (78, 27), (78, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (79, 67), (79, 90), (79, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (80, 43), (80, 70), (80, 2);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (81, 80), (81, 22), (81, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (82, 37), (82, 64), (82, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (83, 71), (83, 6), (83, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (84, 84), (84, 20), (84, 57);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (85, 12), (85, 48), (85, 75);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (86, 50), (86, 87), (86, 24);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (87, 13), (87, 42), (87, 79);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (88, 5), (88, 36), (88, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (89, 21), (89, 45), (89, 70);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (90, 66), (90, 94), (90, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (91, 55), (91, 81), (91, 16);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (92, 88), (92, 28), (92, 53);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (93, 7), (93, 34), (93, 59);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (94, 41), (94, 67), (94, 92);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (95, 1), (95, 26), (95, 63);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (96, 76), (96, 19), (96, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (97, 4), (97, 35), (97, 60);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (98, 58), (98, 85), (98, 10);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (99, 33), (99, 56), (99, 81);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (100, 70), (100, 25), (100, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (101, 15), (101, 42), (101, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (102, 52), (102, 79), (102, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (103, 17), (103, 44), (103, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (104, 36), (104, 61), (104, 90);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (105, 73), (105, 8), (105, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (106, 51), (106, 78), (106, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (107, 13), (107, 38), (107, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (108, 68), (108, 24), (108, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (109, 9), (109, 64), (109, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (110, 87), (110, 29), (110, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (111, 58), (111, 85), (111, 20);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (112, 11), (112, 36), (112, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (113, 71), (113, 91), (113, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (114, 84), (114, 19), (114, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (115, 2), (115, 55), (115, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (116, 64), (116, 33), (116, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (117, 17), (117, 42), (117, 73);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (118, 56), (118, 88), (118, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (119, 11), (119, 37), (119, 76);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (120, 38), (120, 63), (120, 3);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (121, 74), (121, 21), (121, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (122, 39), (122, 65), (122, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (123, 57), (123, 5), (123, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (124, 28), (124, 53), (124, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (125, 86), (125, 14), (125, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (126, 32), (126, 58), (126, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (127, 64), (127, 23), (127, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (128, 9), (128, 46), (128, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (129, 47), (129, 93), (129, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (130, 35), (130, 59), (130, 94);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (131, 82), (131, 31), (131, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (132, 56), (132, 81), (132, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (133, 3), (133, 27), (133, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (134, 67), (134, 90), (134, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (135, 43), (135, 70), (135, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (136, 80), (136, 22), (136, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (137, 58), (137, 85), (137, 10);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (138, 33), (138, 56), (138, 81);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (139, 70), (139, 25), (139, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (140, 15), (140, 42), (140, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (141, 52), (141, 79), (141, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (142, 17), (142, 44), (142, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (143, 36), (143, 61), (143, 6);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (144, 73), (144, 4), (144, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (145, 51), (145, 78), (145, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (146, 13), (146, 38), (146, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (147, 68), (147, 24), (147, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (148, 9), (148, 64), (148, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (149, 87), (149, 29), (149, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (150, 58), (150, 85), (150, 20);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (151, 11), (151, 36), (151, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (152, 71), (152, 6), (152, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (153, 84), (153, 19), (153, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (154, 2), (154, 55), (154, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (155, 64), (155, 33), (155, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (156, 17), (156, 42), (156, 73);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (157, 56), (157, 88), (157, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (158, 11), (158, 37), (158, 76);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (159, 38), (159, 63), (159, 5);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (160, 74), (160, 21), (160, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (161, 39), (161, 65), (161, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (162, 57), (162, 5), (162, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (163, 28), (163, 53), (163, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (164, 86), (164, 14), (164, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (165, 32), (165, 58), (165, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (166, 64), (166, 23), (166, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (167, 9), (167, 46), (167, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (168, 47), (168, 93), (168, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (169, 35), (169, 59), (169, 94);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (170, 82), (170, 31), (170, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (171, 56), (171, 81), (171, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (172, 3), (172, 27), (172, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (173, 67), (173, 90), (173, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (174, 43), (174, 70), (174, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (175, 80), (175, 22), (175, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (176, 58), (176, 85), (176, 10);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (177, 33), (177, 56), (177, 81);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (178, 70), (178, 25), (178, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (179, 15), (179, 42), (179, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (180, 52), (180, 79), (180, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (181, 17), (181, 44), (181, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (182, 36), (182, 61), (182, 9);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (183, 73), (183, 6), (183, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (184, 51), (184, 78), (184, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (185, 13), (185, 38), (185, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (186, 68), (186, 24), (186, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (187, 9), (187, 64), (187, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (188, 87), (188, 29), (188, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (189, 58), (189, 85), (189, 20);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (190, 11), (190, 36), (190, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (191, 71), (191, 9), (191, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (192, 84), (192, 19), (192, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (193, 2), (193, 55), (193, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (194, 64), (194, 33), (194, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (195, 17), (195, 42), (195, 73);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (196, 56), (196, 88), (196, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (197, 11), (197, 37), (197, 76);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (198, 38), (198, 63), (198, 8);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (199, 74), (199, 21), (199, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (200, 39), (200, 65), (200, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (201, 57), (201, 5), (201, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (202, 28), (202, 53), (202, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (203, 86), (203, 14), (203, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (204, 32), (204, 58), (204, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (205, 64), (205, 23), (205, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (206, 9), (206, 46), (206, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (207, 47), (207, 93), (207, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (208, 35), (208, 59), (208, 94);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (209, 82), (209, 31), (209, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (210, 56), (210, 81), (210, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (211, 3), (211, 27), (211, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (212, 67), (212, 90), (212, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (213, 43), (213, 70), (213, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (214, 80), (214, 22), (214, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (215, 58), (215, 85), (215, 10);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (216, 33), (216, 56), (216, 81);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (217, 70), (217, 25), (217, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (218, 15), (218, 42), (218, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (219, 52), (219, 79), (219, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (220, 17), (220, 44), (220, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (221, 36), (221, 61), (221, 9);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (222, 73), (222, 2), (222, 22);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (223, 51), (223, 78), (223, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (224, 13), (224, 38), (224, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (225, 68), (225, 24), (225, 49);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (226, 9), (226, 64), (226, 89);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (227, 87), (227, 29), (227, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (228, 58), (228, 85), (228, 20);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (229, 11), (229, 36), (229, 61);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (230, 71), (230, 6), (230, 41);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (231, 84), (231, 19), (231, 44);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (232, 2), (232, 55), (232, 82);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (233, 64), (233, 33), (233, 68);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (234, 17), (234, 42), (234, 73);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (235, 56), (235, 88), (235, 29);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (236, 11), (236, 37), (236, 76);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (237, 38), (237, 63), (237, 2);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (238, 74), (238, 21), (238, 54);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (239, 39), (239, 65), (239, 86);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (240, 57), (240, 5), (240, 30);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (241, 28), (241, 53), (241, 80);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (242, 86), (242, 14), (242, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (243, 32), (243, 58), (243, 83);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (244, 64), (244, 23), (244, 40);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (245, 9), (245, 46), (245, 71);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (246, 47), (246, 93), (246, 15);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (247, 35), (247, 59), (247, 94);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (248, 82), (248, 31), (248, 52);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (249, 56), (249, 81), (249, 18);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (250, 3), (250, 27), (250, 62);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (251, 67), (251, 90), (251, 25);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (252, 43), (252, 70), (252, 1);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (253, 80), (253, 22), (253, 51);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (254, 58), (254, 85), (254, 10);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (255, 33), (255, 56), (255, 81);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (256, 70), (256, 25), (256, 50);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (257, 15), (257, 42), (257, 77);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (258, 52), (258, 79), (258, 14);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (259, 17), (259, 44), (259, 69);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (260, 36), (260, 61), (260, 91);
INSERT INTO technique_tag (tech_id, tag_id) VALUES (261, 73), (261, 8), (261, 22);