it.todo("Should render with some users selected")
it.todo("Dropdown should show suggestions when query is empty")
it.todo("Exact search in dropdown should show user")
it.todo("User should be added when clicking + in dropdown")
it.todo("User should be removed when clicking 'check' in dropdown")
it.todo("User should be removed when clicking 'cross' in name list")